version: '3'
services:
  postgres:
    image: bitnami/postgresql:16.1.0-debian-11-r19
    container_name: postgres-alunoDB
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
      POSTGRES_DB: academia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: